### ISSUE TITLE
TeporaryDrawer Link from react rputer doesn't work when inside ListItem tag

### ISSUE THREAD

**Issue by greggzst** [material-components/material-components-web#1678]
### What MDC-Web Version are you using?

0.25

### What browser(s) is this bug affecting?

Chrome 62

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1.Create simple drawer component like so:
```
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import { TemporaryDrawer, TemporaryDrawerHeader,
    TemporaryDrawerContent } from 'rmwc/Drawer';
import { ListItem } from 'rmwc/List';

class PageDrawer extends Component{
    render(){
        return(
            <TemporaryDrawer>
                 <TemporaryDrawerHeader style={{ backgroundColor: '#f6f6f6' }}>
                    TemporaryDrawerHeader
                </TemporaryDrawerHeader>
                <TemporaryDrawerContent>
                    <ListItem>
                        <Link to='/kasy'>kasy fiskalne</Link>
                    </ListItem>
                </TemporaryDrawerContent>
            </TemporaryDrawer>
        );
    }
}

export default PageDrawer;
```
2.Use component in one of the other components: `<PageDrawer />`
3.Open drawer through react developer tool
4.Click on the link in drawer

### What is the expected behavior?

`Link` should take user to `/kasy`.

### What is the actual behavior?

`Link` doesn't take user anywhere.

### Any other information you believe would be useful?

If I put `Link` outside `ListItem` it works but it loses all of the drawer styles.

**Comment by kfranqueiro** [comment]
This looks like it's related to existing issues e.g. #1004 (both temporary and persistent drawer were affected).

We've merged a fix in 3e173e1ddc3bff5c7c9c2d794eeb36a9354ec98c (based on #1138), which refactors out the `stopPropagation` call which prevented these events from bubbling.

**Comment by greggzst** [comment]
@kfranqueiro So should I just update to 0.26 or what?

**Comment by kfranqueiro** [comment]
The fix just went in today, so it's not in any release yet. It will be in 0.27.0 when we cut the next release (which should be next Monday).

**Comment by greggzst** [comment]
Oh I see. Cheers!

**Comment by bonniezhou** [comment]
This has been fixed via 3e173e1ddc3bff5c7c9c2d794eeb36a9354ec98c (based on #1138), which refactors out the `stopPropagation` call in the drawer's click handler.

**Comment by greggzst** [comment]
@kfranqueiro I've updated it and it still doesn't work unless I put `Link` outside `ListItem`.
