### ISSUE TITLE
Menu: List style type shows on Edge

### ISSUE THREAD

**Issue by jfily** [material-components/material-components-web#2198]
Dunno why, but menu are not displaying as expected on Egde :

![image](https://user-images.githubusercontent.com/10220170/35874050-c1cc2d48-0b6b-11e8-8116-7f6a30fde002.png)

Setting the property list-style-type: none; on the li instead of the ul fixes the problem... (Microsoft <3)

**Comment by acdvorak** [comment]
Thanks so much for reporting this!

I recently encountered the same bug in IE 11 💩  while working on the [theme demo page](https://material-components-web.appspot.com/theme/index.html).

(I could have sworn it was fixed in Edge, but I could be wrong.)

I left myself a comment in the [theme demo markup](https://github.com/material-components/material-components-web/blob/665cf12b23745cd406f40186a3a998cad6cc6424/demos/theme/index.html#L51) which points to a [post on Stack Overflow](https://stackoverflow.com/a/23717689/467582). Judging by the responses there - and from my own experimentation - the only workaround for this bug is to add an inline style in the markup: `style="list-style: none"`.

I'll create a PR to mention this pitfall in the mdc-menu README.

Thanks again!

**Comment by kvdheuvel** [comment]
@acdvorak Any news on this problem? We are still encountering this problem with mdc version 0.41 and the latest version of Edge.

**Comment by abhiomkar** [comment]
I'm no longer able to reproduce this issue with [MDC Menu](https://material-components.github.io/material-components-web-catalog/#/component/menu) - tested this on IE 11 and on MS Edge 41 (EdgeHTML 16) on Windows 10.

**Comment by acdvorak** [comment]
I'm also not able to reproduce this anymore. Tested in IE 11 💩and Edge 16.

@kvdheuvel Are you still seeing this issue with the latest version of `mdc-menu` ([`0.41.0`](https://www.npmjs.com/package/@material/menu/v/0.41.0))?

**Comment by kvdheuvel** [comment]
@acdvorak It looks like this problem only happens when using an `mdc-menu` in the `mdc-top-app-bar`. On any other location it works as expected.

**Comment by abhiomkar** [comment]
I tested this on Edge by rendering menu inside top-app-bar, I still couldn't reproduce this issue.

**Comment by kvdheuvel** [comment]
@abhiomkar I'll try to pinpoint the problem. When I know more I will let you know with what I've found. Thnx for checking anyway (Y)

**Comment by abhiomkar** [comment]
Here is an [example on stackblitz](https://stackblitz.com/edit/mdc-top-app-bar-demo-u3tmrf) that renders menu component inside top app bar for your reference.
