### ISSUE TITLE
https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js seems to be down... I'm getting 404

### ISSUE THREAD

**Issue by sconvine** [material-components/material-components-web#4712]
## Bug report
**https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js seems to be down, I'm getting 404**

### Steps to reproduce
1. Go to https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js

### Actual behavior
doesn't load

### Expected behavior
should load, and has always...

### Screenshots

![image](https://user-images.githubusercontent.com/953045/57659661-6feabb80-7626-11e9-894d-14ff6a7ab286.png)

**Comment by abhiomkar** [comment]
It is fixed now?

**Comment by sconvine** [comment]
Still cannot fink/ 404 
![image](https://user-images.githubusercontent.com/953045/57659863-41211500-7627-11e9-82a1-6421c8310a54.png)

**Comment by abhiomkar** [comment]
Please tag the version number to v2.2.0 so it won’t break your app when we make a major release. 

https://unpkg.com/material-components-web@2.2.0/dist/material-components-web.min.js

Thanks!

**Comment by sconvine** [comment]
Ah ok, fair point. Updated Thanks!
