### ISSUE TITLE
SASS Division and its deprecation notices

### ISSUE THREAD

**Issue by damienfa** [material-components/material-components-web#7143]
## Description

Their is now a lot of "deprecation notices" when compiling the scss files... 
Read this : https://sass-lang.com/documentation/breaking-changes/slash-div

## Acceptance criteria

It could be easy to launch the command `sass-migrator division **/*.scss` and fix it.

**Comment by crisbeto** [comment]
This should've been fixed by https://github.com/material-components/material-components-web/pull/7158, but I don't know if it has made it into a stable release yet.

**Comment by ChadBurggraf** [comment]
Is there a way to backport this change to e.g., a v5.2.0 release? I have a commit that can be turned into a PR [here](https://github.com/dispoteca/material-components-web/commit/047392206f65a607e92ced1739236daf81e37fe6), but there is no branch tracking 5.x to create a PR against.

**Comment by SampsonCrowley** [comment]
Is there an update on this? there was a new release just 2 days ago with 13.0.0, but the changelog still doesn't mention anything about math.div
