### ISSUE TITLE
[checkbox] sass compilation error with last sass "sass@1.40.0"

### ISSUE THREAD

**Issue by ftaiolivista** [material-components/material-components-web#7391]
```
sass --style=expanded --load-path=../node_modules --load-path=/home/vista/dev/iter-mono/iter-web/app/styles --load-path=/home/vista/dev/iter-mono/iter-web --load-path=/home/vista/dev/iter-mono/iter-web/node_modules app/styles/index.scss
Error: Expected "(" or ".".
    ╷
329 │   $checkbox-padding: calc((_ripple-size - _icon-size) / 2);
    │                                        ^
    ╵
  ../node_modules/@material/checkbox/_checkbox-theme.scss 329:40  @use
  ../node_modules/@material/checkbox/_checkbox.scss 42:1          @forward
  ../node_modules/@material/checkbox/_variables.scss 24:1         @forward
  @material/_index.scss 1:1                                       @use
  @vista/iter-theme/app/styles/main.scss 16:1                     @import

```

**Comment by SlickNicky10** [comment]
The same issue is occurring with dialog.

```
Error: Expected "(" or ".".
    ╷
834 │       calc(title - 2 * close),
    │                 ^
    ╵
  node_modules\@material\dialog\_mixins.scss 834:17  @forward
  node_modules\@material\dialog\_index.scss 2:1      @use
  node_modules\@smui\dialog\_style.scss 1:1          @use
  node_modules\smui-theme\_style.scss 9:1            @use
  node_modules\smui-theme\_index.scss 2:1            root stylesheet
```

**Comment by shvlv** [comment]
Look like this is caused by https://github.com/sass/dart-sass/releases/tag/1.40.0.

**Comment by ftaiolivista** [comment]
> This may break your stylesheets, but only if they were already producing broken CSS.

**Comment by dfreedm** [comment]
Looks like sass is parsing templated `calc()` expressions used by `@theme.property()` now.
https://github.com/material-components/material-components-web/blob/master/packages/mdc-checkbox/_checkbox-theme.scss#L329-L336

**Comment by aomarks** [comment]
Found a few other spots, but they'll be fixed in https://github.com/material-components/material-components-web/pull/7402

**Comment by melknooHansNatur** [comment]
Is there a fix for this now? Do I need to update anything? Still getting the error :(
